version: '20.10.22'
services:
  client:
    build: ./client
    container_name: client_c
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - /app/node_modules
  server:
    build: ./server
    container_name: server_c
    ports:
      - '5000:5000'
    stdin_open: true
    tty: true
